output_directory: runs/production
random_seed: 42

dataset:
  mirror: true
  dataset_paths:
    - ./datasets/synthetic
    - ./datasets/cantoon/monsters_university
    - ./datasets/game/death_stranding/
    - ./datasets/kpop/le_sserafim_antifragile
    - ./datasets/kpop/newjeans_attention
    - ./datasets/movie/john_wick_05x/
    - ./datasets/sport/alysa_liu_stateside_1x/
    - ./datasets/sport/alysa_liu_stateside_025x/
  val_dataset_paths:
    - ./datasets/val/alysa_liu_stateside_025x
    - ./datasets/val/death_stranding
    - ./datasets/val/newjeans_attention
  validation_batch_size: 2

model_architecture:
  model_name: ArtRT
  d_model: 64
  d_state: 64
  expand: 4
  chunk_size: 64
  compile: default

training_settings:
  batch_size: 10
  num_epochs: 100
  lr:
    peak: 5.0e-5
    min: 1.0e-6
    period: 30
  weight_decay: 1.0e-4
  adam_beta1: 0.9
  adam_beta2: 0.95
  gradient_clipping_threshold: 5.0
  gradient_accumulation_steps: 2

schedule:
  - epoch: 1+
    weights:
      charbonnier: 5.0
      haarpsi: 5.0
      gmsd: 0.5

logging_settings:
  log_interval: 100
  validation_interval: 1

memory_settings:
  max_ram_ratio: 0.5
  max_vram_ratio: 0.8
  check_interval: 256
