output_directory: runs/production
random_seed: 42

dataset:
  mirror: true
  dataset_paths:
    - ./datasets/synthetic
    - ./datasets/cantoon/monsters_university
    - ./datasets/game/death_stranding/
    - ./datasets/kpop/le_sserafim_antifragile
    - ./datasets/kpop/newjeans_attention
    - ./datasets/movie/john_wick_05x/
    - ./datasets/sport/alysa_liu_stateside_1x/
    - ./datasets/sport/alysa_liu_stateside_025x/
  val_dataset_paths:
    - ./datasets/val/alysa_liu_stateside_025x
    - ./datasets/val/death_stranding
    - ./datasets/val/newjeans_attention
  validation_batch_size: 5

model_architecture:
  model_name: ArtRT
  dim: 48
  n1: 8
  n2: 8
  n3: 8
  nmid: 8
  compile: default

training_settings:
  batch_size: 10
  num_epochs: 1000
  optimizer: prodigy
  prodigy:
    lr: 0.1
    weight_decay: 1.0e-4
    gradient_clipping_threshold: 1.0
    gradient_accumulation_steps: 10
    betas: [0.9, 0.999]
    beta3: 0.99
    d0: 1.0e-6
    safeguard_warmup: true
  adamw:
    lr: 5.0e-5
    weight_decay: 1.0e-4
    gradient_clipping_threshold: 1.0
    gradient_accumulation_steps: 2
    betas: [0.9, 0.999]
  sophia:
    lr: 1.0e-4
    weight_decay: 1.0e-1
    gradient_clipping_threshold: 1.0
    gradient_accumulation_steps: 2
    betas: [0.9, 0.95]
    rho: 0.04
    hessian_update_freq: 10

schedule:
  - epoch: 1+
    weights:
      charbonnier: 0.95
      fft: 0.01
      fbin: 0.04

logging_settings:
  log_interval: 100
  validation_interval: 1
